add easy to use env support
dataquest-dev/dspace-python-api pull request #132
Opened 2024-03-06 14:02 UTC by MajoBerger

I needed a simple way to modify config. It is not a general solution, which could come in handy, but would be too extensive to implement now.

2024-03-07 06:24 UTC, MajoBerger commented
This is not the most general solution, but I am afraid I would waste my time with developing very general solution, as it will not be always required and I think my suggestions would get rejected.

2024-03-11 09:00 UTC, vidiecan requested changes

2024-03-11 09:00 UTC, vidiecan commented on tools/create_bitstreams/create_bitstreams.py
> +# abcd = os.getenv(")
abcd?

2024-03-11 12:05 UTC, MajoBerger commented
also add to readme and  to logs!

2024-03-18 06:54 UTC, merged