80-PY/import-tasklistitem
dataquest-dev/dspace-python-api pull request #39
Opened 2023-06-02 13:12 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  1  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
Import data from table tasklistitem into table cwf_pooltask.
## Analysis
Add epersons from tasklistitem table into correct group correcsponding their workflowitem.

2023-06-02 14:04 UTC, milanmajchrak requested changes

2023-06-02 14:04 UTC, milanmajchrak commented on dspace_import.py
> +        params = {'epersonUUID': eperson_id[i['eperson_id']], 'workflowitem_id': workflowitem_id[i['workflow_id']]}
Maybe add params into `try` clause because if something will be missing in the json the migration will be stopped

2023-06-02 14:55 UTC, milanmajchrak approved these changes

2023-06-14 07:15 UTC, mrovnanik approved these changes

2023-06-14 07:58 UTC, merged