Internal/data migration continue
dataquest-dev/dspace-python-api pull request #5
Opened 2023-03-30 08:02 UTC by Paurikova2

Continue of data migration.

2023-05-02 14:40 UTC, mrovnanik requested changes

2023-05-02 14:40 UTC, mrovnanik commented on migration_const.py
This way? Use other constant or no value at all

2023-05-03 13:09 UTC, milanmajchrak commented on migration_const.py
fixed

2023-05-03 14:07 UTC, mrovnanik approved these changes

2023-05-03 14:10 UTC, merged