ufal/py-collection2item-table-is-not-migrated
dataquest-dev/dspace-python-api pull request #94
Opened 2023-09-21 14:23 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  7  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2023-09-22 07:52 UTC, Paurikova2 requested changes

2023-09-22 07:52 UTC, Paurikova2 commented on data_pump/item.py
> +        if item_uuid in coll_2_item_dict:
maybe use opposite condition, there will be less tabs

2023-09-22 07:52 UTC, Paurikova2 commented on support/dspace_interface/client.py
> +        @param content_type:
missing comment

2023-10-03 07:12 UTC, MajoBerger approved these changes

2023-10-03 07:16 UTC, merged